services:
  postgres:
    image: postgres
    container_name: postgres-db
    restart: always
    shm_size: 128mb
    ports:
      - 5442:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - web-app-network
    volumes:
      - postgres_db:/var/lib/postgresql/data

  app:
    image: one-time-links
    container_name: one-time-links
    restart: always
    working_dir: /app
    build:
      context: .
    ports:
      - '${PORT}:3000'
    command: >
      bash -c "
      apt-get update -y &&
      apt-get install -y openssl &&
      npx prisma generate &&
      npm run start:dev
      "
    networks:
      - web-app-network
    volumes:
      - ./:/app

networks:
  web-app-network:
    name: web-app-network
    external: true
volumes:
  postgres_db:
    name: postgres_db_data
